language: node_js
node_js:
  - node
  - '10'
  - '8'
  - '6'
before_install:
  - npm install -g npm
script: npm test
after_success:
  - cat ./coverage/lcov.info | ./node_modules/.bin/coveralls
jobs:
  include:
    - stage: release
      node_js: lts/*
      before_install:
        - npm install -g npm
      install:
        - travis_retry npm install
      before_script: skip
      script: npm run semantic-release
      after_success: skip
      after_failure: skip
      after_script: skip
cache:
  directories:
    - ~/.npm
